# Generated by Django 4.1.5 on 2023-01-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profiles'),
        ),
    ]
