# Generated by Django 4.1.5 on 2023-01-07 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cents', '0002_alter_cent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cents', to='cents.category'),
        ),
    ]
