# Generated by Django 4.1.5 on 2023-01-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cents', '0003_like_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cent',
            name='loves',
            field=models.IntegerField(null=True),
        ),
    ]
