# Generated by Django 4.1.5 on 2023-01-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cents', '0004_cent_loves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cent',
            name='loves',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
