# Generated by Django 4.1.5 on 2023-01-08 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cents', '0005_alter_cent_loves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cent',
            name='loves',
        ),
        migrations.AddField(
            model_name='cent',
            name='hearts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cent',
            name='user_likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='already_liked',
            field=models.BooleanField(default=False),
        ),
    ]
